spring:
  application:
    name: ledger-service
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
firebase:
  credentials: ${GOOGLE_APPLICATION_CREDENTIALS:}
  project-id: ${FIREBASE_PROJECT_ID:}
---
spring:
  config:
    activate:
      on-profile: prod
firebase:
  credentials: ${GOOGLE_APPLICATION_CREDENTIALS:}
  project-id: ${FIREBASE_PROJECT_ID:}
