version: "3.9"
services:
  ledger-service:
    image: ghcr.io/wiremock/wiremock:3.6.0
    container_name: ledger-service
    ports:
      - "8081:8080"
    volumes:
      - ./stubs/ledger:/home/wiremock
    environment:
      - WIREMOCK_OPTIONS=--global-response-templating
  risk-service:
    image: ghcr.io/wiremock/wiremock:3.6.0
    container_name: risk-service
    ports:
      - "8082:8080"
    volumes:
      - ./stubs/risk:/home/wiremock
  notification-service:
    image: ghcr.io/wiremock/wiremock:3.6.0
    container_name: notification-service
    ports:
      - "8083:8080"
    volumes:
      - ./stubs/notifications:/home/wiremock
